Mvc.DynamicMenu/Models/ErrorViewModel.cs
using System;

namespace Mvc.DynamicMenu.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Mvc.DynamicMenu/Models/NavigationMenuViewModel.cs
using System;

namespace Mvc.DynamicMenu.Models
{
	public class NavigationMenuViewModel
	{
		public Guid Id { get; set; }

		public string Name { get; set; }

		public Guid? ParentMenuId { get; set; }

		public string ControllerName { get; set; }

		public string ActionName { get; set; }

		public bool Permitted { get; set; }
	}
}

Mvc.DynamicMenu/Models/RoleViewModel.cs
namespace Mvc.DynamicMenu.Models
{
	public class RoleViewModel
	{
		public string Id { get; set; }

		public string Name { get; set; }
	}
}

Mvc.DynamicMenu/Models/UserViewModel.cs
namespace Mvc.DynamicMenu.Models
{
	public class UserViewModel
	{
		public string Id { get; set; }

		public string UserName { get; set; }

		public string Email { get; set; }
	}
}

Mvc.DynamicMenu/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Mvc.DynamicMenu.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mvc.DynamicMenu.Controllers
{
	public class AdministrationController : Controller
	{
		private readonly UserManager<IdentityUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
		private readonly ILogger<AdministrationController> _logger;

		public AdministrationController(
				UserManager<IdentityUser> userManager,
				RoleManager<IdentityRole> roleManager,
				ILogger<AdministrationController> logger)
		{
			_userManager = userManager;
			_roleManager = roleManager;
			_logger = logger;
		}

		public async Task<IActionResult> Roles()
		{
			var roleViewModel = new List<RoleViewModel>();

			try
			{
				var roles = await _roleManager.Roles.ToListAsync();
				foreach (var item in roles)
				{
					roleViewModel.Add(new RoleViewModel()
					{
						Id = item.Id,
						Name = item.Name,
					});
				}
			}
			catch (Exception ex)
			{
				_logger?.LogError(ex, ex.GetBaseException().Message);
			}

			return View(roleViewModel);
		}

		public async Task<IActionResult> Users()
		{
			var userViewModel = new List<UserViewModel>();

			try
			{
				var users = await _userManager.Users.ToListAsync();
				foreach (var item in users)
				{
					userViewModel.Add(new UserViewModel()
					{
						Id = item.Id,
						Email = item.Email,
						UserName = item.UserName,
					});
				}
			}
			catch (Exception ex)
			{
				_logger?.LogError(ex, ex.GetBaseException().Message);
			}

			return View(userViewModel);
		}
	}
}

Mvc.DynamicMenu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mvc.DynamicMenu.Models;

namespace Mvc.DynamicMenu.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Mvc.DynamicMenu/ViewComponents/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mvc.DynamicMenu.Services;
using System.Threading.Tasks;

namespace Mvc.DynamicMenu.ViewComponents
{
	public class NavigationMenuViewComponent : ViewComponent
	{
		private readonly IDataAccessService _dataAccessService;

		public NavigationMenuViewComponent(IDataAccessService dataAccessService)
		{
			_dataAccessService = dataAccessService;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var items = await _dataAccessService.GetMenuItemsAsync(HttpContext.User);

			return View(items);
		}
	}
}

Mvc.DynamicMenu/Views/Administration/Roles.cshtml
@model IEnumerable<Mvc.DynamicMenu.Models.RoleViewModel>
@{
	ViewData["Title"] = "Roles";
}
<h1>Roles</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Id)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
			</tr>
		}
	</tbody>
</table>

Mvc.DynamicMenu/Views/Administration/Users.cshtml
@model IEnumerable<Mvc.DynamicMenu.Models.UserViewModel>
@{
	ViewData["Title"] = "Users";
}

<h1>Users</h1>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.UserName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Email)
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.UserName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Email)
				</td>
			</tr>
		}
	</tbody>
</table>

Mvc.DynamicMenu/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc.DynamicMenu/Views/Shared/Components/NavigationMenu/Default.cshtml
@model List<Mvc.DynamicMenu.Models.NavigationMenuViewModel>
@{
	ViewData["Title"] = "NavigationMenu";
}
<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dynamic Menu</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarsExampleDefault">
	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
			<a class="nav-link text" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
		</li>
		@*Menu Items from the database*@
		@foreach (var item in Model)
		{
			if (item.ParentMenuId == null) //Level one items will have null parent id
			{
				if (!string.IsNullOrWhiteSpace(item.ControllerName))
				{
					<li class="nav-item active">
						<a class="nav-link text" asp-area="" asp-controller="@item.ControllerName" asp-action="@item.ActionName">@item.Name</a>
					</li>
				}
				var children = Model.Where(x => x.ParentMenuId == item.Id).ToList();
				if (children != null)
				{
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@item.Name</a>
						<div class="dropdown-menu" aria-labelledby="dropdown01">
							@foreach (var itm in children)
							{
								<a class="dropdown-item" asp-area="" asp-controller="@itm.ControllerName" asp-action="@itm.ActionName">@itm.Name</a>
							}
						</div>
					</li>
				}
			}
		}
	</ul>
	<partial name="_LoginPartial" />
</div>

Mvc.DynamicMenu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Mvc.DynamicMenu</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
			  crossorigin="anonymous"
			  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
	</environment>
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			@await Component.InvokeAsync("NavigationMenu")
		</nav>
	</header>
	<div class="container">
		<partial name="_CookieConsentPartial" />
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2019 - Mvc.DynamicMenu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
		</script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
		</script>
	</environment>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@RenderSection("Scripts", required: false)
</body>
</html>